site_name: Paonia
nav:
  - Welcome: index.md
  - Control Center: 
    - Overview: control_center/index.md
  - Atomics:
    - Overview: atomics/index.md
    - API v1:
      - Getting started: atomics/api/v1/index.md
      - Authentication: atomics/api/v1/auth.md
      - Resources:
        - Atomics: atomics/api/v1/resources/atomics.md
        - Compute: atomics/api/v1/resources/compute.md
  - Identity and Access Management (IAM): 
    - Overview: iam/index.md
    - Service user: iam/service_user.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: img/paonia.png
  favicon: img/paonia.png
  palette:
    scheme: paonia-light
    # accent: pink
    # primary: white

  repo_url: https://gitlab.com/boc-lab/atomics
  features:
    - content.code.annotate

copyright: "Copyright &copy; 2022 Hifield; 2022 Paonia"

markdown_extensions:
  - meta
  - attr_list
  - def_list
  - admonition
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true