site_name: Documentation
nav:
  - Welcome: index.md
  - Atomics:
    - Rest API v1: 
      - Getting Started: atomics/rest_api_v1/getting_started.md
      - Get IP mutualization status: atomics/rest_api_v1/get_ip_mutualization_status.md
      - Get related services: atomics/rest_api_v1/get_related_services.md
      - Search related threats: atomics/rest_api_v1/search_related_threats.md
      - Enhanced Whois: atomics/rest_api_v1/enhanced_whois.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: img/paonia_logo_text_darkpink_01.png
  favicon: img/paonia.png
  palette:
    scheme: paonia-light
    accent: pink
    primary: white

  features:
    - content.code.annotate

copyright: "Copyright &copy; 2022 Hifield; 2022 Paonia"

markdown_extensions:
  - meta
  - attr_list
  - def_list
  - admonition
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true