site_name: Documentation
nav:
  - Welcome: index.md
  - API:
    - Getting Started: api/getting_started.md
    - Assets Search:
      - Get IP mutualization status: api/assets_search/get_ip_mutualization_status.md
      - Get related services: api/assets_search/get_related_services.md
      - Search related threats: api/assets_search/search_related_threats.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: img/rb_logo_wide.png
  favicon: img/r_logo_sm_border.png
  palette:
    scheme: riskboard-light
    accent: pink
    primary: white

  features:
    - content.code.annotate

copyright: "Copyright &copy; 2023 Almond"

markdown_extensions:
  - meta
  - attr_list
  - def_list
  - admonition
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
#  - markdown_include.include:
#      base_path: content/includes/
#      encoding: utf-8
  - toc:
      permalink: true